name: gmi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0
  wakelock_plus: ^1.2.4
  shared_preferences: ^2.2.3
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1
  video_player: ^2.9.2
  chewie: ^1.8.1
  cupertino_icons: ^1.0.8
  responsive_framework: ^1.1.1
  audioplayers: ^6.5.1
  google_fonts: ^6.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0891B2"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_padding: 20

flutter:
  uses-material-design: true
  assets:
    - assets/images/alphabet/
    - assets/images/number/
    - assets/images/colour/
    - assets/images/animal/
    - assets/images/fruit/
    - assets/images/verb/
    - assets/images/speech/
    - assets/images/
    - assets/videos/alphabet/
    - assets/videos/numbers/
    - assets/videos/colours/
    - assets/videos/fruits/
    - assets/videos/animals/
    - assets/videos/verbs/
    - assets/videos/speech/
    - assets/images/mfd.jpg
    - assets/images/logo.png
    - assets/images/google.png
    - assets/gifs/trophy_quiz.gif
    - assets/audio/streak.wav
    - assets/audio/level_complete.wav
    - assets/audio/click.mp3
